import Link from "next/link";
import { createClient } from "@/lib/supabase/server";

export default async function Home() {
  const supabase = await createClient();

  // Obtener eventos activos
  const { data: eventos } = await supabase
    .from('eventos')
    .select('*')
    .eq('activo', true)
    .order('orden', { ascending: true }) as any;

  return (
    <div className="min-h-screen font-[family-name:var(--font-geist-sans)]">
      {/* Navbar Simple */}
      <nav className="bg-white/80 backdrop-blur-md sticky top-0 z-50 border-b border-gray-100">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-center h-16 items-center">
            <span className="text-2xl font-bold bg-gradient-to-r from-purple-600 to-pink-600 text-transparent bg-clip-text">
              Eventos Maranatha
            </span>
          </div>
        </div>
      </nav>

      <main>
        {/* Hero Section */}
        <div className="relative bg-gray-900 py-24 sm:py-32 overflow-hidden">
          <div className="absolute inset-0">
            <img
              src="https://images.unsplash.com/photo-1513151233558-d860c5398176?q=80&w=2070&auto=format&fit=crop"
              alt="Background"
              className="w-full h-full object-cover opacity-40"
            />
            <div className="absolute inset-0 bg-gradient-to-t from-gray-900 via-gray-900/40" />
          </div>

          <div className="relative max-w-7xl mx-auto px-6 text-center lg:px-8">
            <h1 className="text-4xl font-bold tracking-tight text-white sm:text-6xl mb-6">
              Creamos momentos inolvidables
            </h1>
            <p className="text-lg leading-8 text-gray-300 max-w-2xl mx-auto mb-10">
              Decoraciones, arreglos y todo lo que necesitas para hacer de tu evento algo único y especial.
            </p>
            <div className="flex gap-4 justify-center">
              <Link href="#eventos" className="bg-white text-gray-900 px-6 py-3 rounded-full font-semibold hover:bg-gray-100 transition">
                Ver Catálogo
              </Link>
              <Link href="https://wa.me/51999999999" target="_blank" className="bg-green-600 text-white px-6 py-3 rounded-full font-semibold hover:bg-green-700 transition">
                Contactar por WhatsApp
              </Link>
            </div>
          </div>
        </div>

        {/* Categories / Events Section */}
        <div id="eventos" className="max-w-7xl mx-auto px-6 py-24 lg:px-8">
          <h2 className="text-3xl font-bold text-center text-gray-900 mb-12">Nuestros Servicios</h2>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {eventos?.map((evento: any) => (
              <Link href={`/eventos/${evento.id}`} key={evento.id} className="group">
                <div className="relative h-64 rounded-2xl overflow-hidden bg-gray-100 shadow-lg transition-transform duration-300 group-hover:-translate-y-2">
                  {/* Placeholder image generated by color or default */}
                  <div className={`absolute inset-0 bg-gray-200`}>
                    {evento.imagen_url ? (
                      <img src={evento.imagen_url} alt={evento.nombre} className="w-full h-full object-cover" />
                    ) : (
                      <div className="w-full h-full bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center">
                        <span className="text-white font-bold opacity-30">Sin Foto</span>
                      </div>
                    )}
                  </div>

                  <div className="absolute inset-0 flex flex-col justify-end p-6 bg-gradient-to-t from-black/60 via-transparent">
                    <h3 className="text-2xl font-bold text-white">{evento.nombre}</h3>
                    {evento.descripcion && <p className="text-gray-200 text-sm mt-2 line-clamp-2">{evento.descripcion}</p>}
                  </div>
                </div>
              </Link>
            ))}

            {(!eventos || eventos.length === 0) && (
              <div className="col-span-full text-center py-12 bg-gray-50 rounded-xl border border-dashed border-gray-300">
                <p className="text-gray-500">Aún no hemos publicado eventos. ¡Vuelve pronto!</p>
              </div>
            )}
          </div>
        </div>

        {/* Footer */}
        <footer className="bg-white border-t border-gray-100 py-12">
          <div className="max-w-7xl mx-auto px-6 text-center">
            <p className="text-gray-500">© {new Date().getFullYear()} Eventos Maranatha. Todos los derechos reservados.</p>
          </div>
        </footer>
      </main>
    </div>
  );
}
